# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# To make it work, go to the repository settings, then Options, GitHub Pages and select `gh-pages` under Source.
name: Publish the demo
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish the demo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Node packages
        run: yarn install
      - name: Build the demo
        run: yarn playground:build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: playground/dist
          CLEAN: true
          SINGLE_COMMIT: true
      - name: Print the demo URL
        run: echo "âœ… The demo has been deployed to https://$(cut -d'/' -f1 <<< $GITHUB_REPOSITORY).github.io/$(cut -d'/' -f2 <<< $GITHUB_REPOSITORY)/"
